[build]
publish = "dist"
command = "npm run production"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
from = "/posts/*"
to = "/blog/:splat"
status = 301
force = true

[[redirects]]
from = "/talks"
to = "/pages/talks"
status = 301
force = true

[[redirects]]
from = "/uses"
to = "/pages/uses"
status = 301
force = true

# Redirects for old URLs of blog posts pre-2019
[[redirects]]
from = "/consider-using-typescript/"
to = "/posts/why-you-might-want-to-consider-using-typescript-6j3/"
status = 301
force = true

[[redirects]]
from = "/blog/2020-01-21-a-new-year-a-new-start-im-joining-the-dev-team/"
to = "/posts/a-new-year-a-new-start-i-m-joining-the-dev-team-3ap0/"
status = 301
force = true

[[redirects]]
from = "/great-pr/"
to = "https://dev.to/nickytonline/great-examples-of-issues-and-pull-requests-2nne"
status = 301
force = true

[[redirects]]
from = "/pair/"
to = "https://airtable.com/shrr10gmF5YxhY3W0"
status = 301
force = true

[[redirects]]
from = "/hacktoberfest2020/"
to = "https://www.digitalocean.com/community/tech_talks/getting-the-most-out-of-open-source"
status = 301
force = true

[[redirects]]
from = "/lightning2020/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vRHfnRD5-ZTiPbBZsT3fNtsB4KcKiemJCLhUxPjtGE5nR2JxmtbtK3_iLSeYbg3ctgVAJEiqPSnAVUQ/pub?start=false&loop=false&delayms=3000"
status = 301
force = true

[[redirects]]
from = "/storybook2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vRVZS5fW795LoPUioxbpIO0k0gaUA7g-J9je8bCaoHKGl678_NgbpNXdsiw3HIrt5BHTLr_l2MmvaNU/pub?start=false&loop=false&delayms=5000"
status = 301
force = true

[[redirects]]
from = "/debug2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vSPMh7JIhImdVWJxUJQOICyib6uETKfpXZ9PDpO-6p-qxn3gW2QxKJHj2ofMxi_s31gAhnwl0nWugOQ/pub?start=false&loop=false&delayms=5000"
status = 301
force = true

[[redirects]]
from = "https://youtube.iamdeveloper.com/*"
to = "https://youtube.com/@iamdeveloperdotcom/:splat"
status = 301
force = true

[[redirects]]
from = "https://livecoding.ca/learn-rust/*"
to = "https://www.youtube.com/playlist?list=PLcR4ZgxWXeIAFF1MYfuoGa6FeksKcMz-O"
status = 301
force = true

[[redirects]]
from = "https://livecoding.ca/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.livecoding.ca/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://structuredyolo.com/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.structuredyolo.com/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://javascripthours.com/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.javascripthours.com/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://newsletter.iamdeveloper.com"
to = "https://news.iamdeveloper.com"
status = 301
force = true

[[redirects]]
from = "https://news.iamdeveloper.com"
to = "https://iamdeveloper.com/pages/newsletter/"
status = 301
force = true

[[redirects]]
from = "/stream2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vR0cBGMDt11jQ3tP-Z8UPf6BFYXLWX8XzsmfCb26RAYd5gX_ct662YJQrk-fCVp0MOv9tUW4mvBgam8/pub?start=false&loop=false&delayms=5000"
status = 301
force = true

[[redirects]]
from = "/hacktoberfest2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vTUIycMPdV3wRo_nLOhfpiYiUYeML5Bvu4aA1W692VOsvA5p3XIQEC-Y5fPEGWk4uGkpP_z2QNJkJGR/pub?start=false&loop=false&delayms=5000"
status = 301
force = true

[[redirects]]
from = "/codementor2022/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vQWw0j07xs3gzh8QOUQH6V5kdtX6xPCMmdnSWBfcniNUgqPTYDeMm2CB3BzdiTG0LOKKKg-Ky8r21ko/pub?start=false&loop=false&delayms=5000"
status = 301
force = true

[[redirects]]
from = "https://book.iamdeveloper.com/*"
to = "https://calendly.com/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "/11tyMeetupMay2022/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vSSj2W1UDxVH2nNBhH0O_5CNia76ri2C0fx8jygK1ZDE6EXs6_CFUZQp64-zyciFaV7xhJWFSYoLsb7/pub?start=false&loop=false&delayms=5000"
status = 301
force = true

[[redirects]]
from = "https://pod.iamdeveloper.com/2065897/*"
to = "https://pod.iamdeveloper.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://pod.iamdeveloper.com/*"
to = "https://nickscuts.buzzsprout.com/2065897/:splat"
status = 301
force = true

[[redirects]]
from = "https://live.iamdeveloper.com/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://iamdeveloper.live/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.iamdeveloper.live/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://vscodetips.com/"
to = "https://iamdeveloper.com/pages/vscode-tips/"
status = 301
force = true

[[redirects]]
from = "https://community.vscodetips.com/"
to = "https://iamdeveloper.com/pages/vscode-tips/"
status = 301
force = true

[[redirects]]
from = "/coc/*"
to = "/pages/coc/:splat"
status = 301
force = true

[[redirects]]
from = "https://discord.iamdeveloper.com/*"
to = "https://discord.gg/FkGSHMxbTe"
status = 301
force = true